/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FreeAuditRouteImport } from './routes/free-audit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhoWeServePoliticalAdvocacyRouteImport } from './routes/who-we-serve.political-advocacy'
import { Route as IndustriesLegalRouteImport } from './routes/industries.legal'
import { Route as IndustriesHomeServicesRouteImport } from './routes/industries.home-services'
import { Route as IndustriesHealthcareRouteImport } from './routes/industries.healthcare'
import { Route as IndustriesAutoDealersRouteImport } from './routes/industries.auto-dealers'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAuditRoute = FreeAuditRouteImport.update({
  id: '/free-audit',
  path: '/free-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeServePoliticalAdvocacyRoute =
  WhoWeServePoliticalAdvocacyRouteImport.update({
    id: '/who-we-serve/political-advocacy',
    path: '/who-we-serve/political-advocacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesLegalRoute = IndustriesLegalRouteImport.update({
  id: '/industries/legal',
  path: '/industries/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHomeServicesRoute = IndustriesHomeServicesRouteImport.update({
  id: '/industries/home-services',
  path: '/industries/home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHealthcareRoute = IndustriesHealthcareRouteImport.update({
  id: '/industries/healthcare',
  path: '/industries/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesAutoDealersRoute = IndustriesAutoDealersRouteImport.update({
  id: '/industries/auto-dealers',
  path: '/industries/auto-dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/free-audit': typeof FreeAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/auto-dealers': typeof IndustriesAutoDealersRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/home-services': typeof IndustriesHomeServicesRoute
  '/industries/legal': typeof IndustriesLegalRoute
  '/who-we-serve/political-advocacy': typeof WhoWeServePoliticalAdvocacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/free-audit': typeof FreeAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/auto-dealers': typeof IndustriesAutoDealersRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/home-services': typeof IndustriesHomeServicesRoute
  '/industries/legal': typeof IndustriesLegalRoute
  '/who-we-serve/political-advocacy': typeof WhoWeServePoliticalAdvocacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/free-audit': typeof FreeAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/auto-dealers': typeof IndustriesAutoDealersRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/home-services': typeof IndustriesHomeServicesRoute
  '/industries/legal': typeof IndustriesLegalRoute
  '/who-we-serve/political-advocacy': typeof WhoWeServePoliticalAdvocacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/free-audit'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/results'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/blog/$slug'
    | '/industries/auto-dealers'
    | '/industries/healthcare'
    | '/industries/home-services'
    | '/industries/legal'
    | '/who-we-serve/political-advocacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/free-audit'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/results'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/blog/$slug'
    | '/industries/auto-dealers'
    | '/industries/healthcare'
    | '/industries/home-services'
    | '/industries/legal'
    | '/who-we-serve/political-advocacy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/free-audit'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/results'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/blog/$slug'
    | '/industries/auto-dealers'
    | '/industries/healthcare'
    | '/industries/home-services'
    | '/industries/legal'
    | '/who-we-serve/political-advocacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  FreeAuditRoute: typeof FreeAuditRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  IndustriesAutoDealersRoute: typeof IndustriesAutoDealersRoute
  IndustriesHealthcareRoute: typeof IndustriesHealthcareRoute
  IndustriesHomeServicesRoute: typeof IndustriesHomeServicesRoute
  IndustriesLegalRoute: typeof IndustriesLegalRoute
  WhoWeServePoliticalAdvocacyRoute: typeof WhoWeServePoliticalAdvocacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-audit': {
      id: '/free-audit'
      path: '/free-audit'
      fullPath: '/free-audit'
      preLoaderRoute: typeof FreeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-serve/political-advocacy': {
      id: '/who-we-serve/political-advocacy'
      path: '/who-we-serve/political-advocacy'
      fullPath: '/who-we-serve/political-advocacy'
      preLoaderRoute: typeof WhoWeServePoliticalAdvocacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/legal': {
      id: '/industries/legal'
      path: '/industries/legal'
      fullPath: '/industries/legal'
      preLoaderRoute: typeof IndustriesLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/home-services': {
      id: '/industries/home-services'
      path: '/industries/home-services'
      fullPath: '/industries/home-services'
      preLoaderRoute: typeof IndustriesHomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/healthcare': {
      id: '/industries/healthcare'
      path: '/industries/healthcare'
      fullPath: '/industries/healthcare'
      preLoaderRoute: typeof IndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/auto-dealers': {
      id: '/industries/auto-dealers'
      path: '/industries/auto-dealers'
      fullPath: '/industries/auto-dealers'
      preLoaderRoute: typeof IndustriesAutoDealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  FreeAuditRoute: FreeAuditRoute,
  HowItWorksRoute: HowItWorksRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  IndustriesAutoDealersRoute: IndustriesAutoDealersRoute,
  IndustriesHealthcareRoute: IndustriesHealthcareRoute,
  IndustriesHomeServicesRoute: IndustriesHomeServicesRoute,
  IndustriesLegalRoute: IndustriesLegalRoute,
  WhoWeServePoliticalAdvocacyRoute: WhoWeServePoliticalAdvocacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
